{{- if and .Values.cert-manager.enabled .Values.cert-manager.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert-manager.clusterIssuer.name }}
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
