{{- if and .Values.vault.tls.enabled .Values.vault.tls.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "vault-pki.fullname" . }}
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.vault.tls.secretName | default (printf "%s-tls" (include "vault-pki.fullname" .)) }}
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Vault PKI
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "vault-pki.fullname" . }}
    - {{ include "vault-pki.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "vault-pki.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "vault-pki.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - "*.{{ include "vault-pki.fullname" . }}-internal"
    - "*.{{ include "vault-pki.fullname" . }}-internal.{{ .Release.Namespace }}"
    - "*.{{ include "vault-pki.fullname" . }}-internal.{{ .Release.Namespace }}.svc"
    - "*.{{ include "vault-pki.fullname" . }}-internal.{{ .Release.Namespace }}.svc.cluster.local"
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: {{ .Values.vault.tls.certManager.issuerName }}
    kind: {{ .Values.vault.tls.certManager.issuerKind }}
{{- end }}
