{{- if .Values.vault.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-pki.serviceAccountName" . }}
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
  {{- with .Values.vault.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
