apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-pki.fullname" . }}
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
  {{- with .Values.vault.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.vault.service.type }}
  ports:
    - port: {{ .Values.vault.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.vault.service.type "NodePort") .Values.vault.service.nodePort) }}
      nodePort: {{ .Values.vault.service.nodePort }}
      {{- end }}
  selector:
    {{- include "vault-pki.selectorLabels" . | nindent 4 }}
---
# Internal service for Vault HA communication
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-pki.fullname" . }}-internal
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
    - name: https-internal
      port: 8201
      targetPort: 8201
      protocol: TCP
  selector:
    {{- include "vault-pki.selectorLabels" . | nindent 4 }}
