{{- if .Values.softhsm.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vault-pki.fullname" . }}-softhsm
  labels:
    {{- include "vault-pki.labels" . | nindent 4 }}
    app.kubernetes.io/component: softhsm
spec:
  selector:
    matchLabels:
      {{- include "vault-pki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: softhsm
  template:
    metadata:
      labels:
        {{- include "vault-pki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: softhsm
    spec:
      serviceAccountName: {{ include "vault-pki.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.softhsm.securityContext | nindent 8 }}
      containers:
        - name: softhsm
          image: "{{ .Values.softhsm.image.repository }}:{{ .Values.softhsm.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.softhsm.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /softhsm/tokens
              cp /etc/softhsm2/softhsm2.conf /tmp/softhsm2.conf
              export SOFTHSM2_CONF=/tmp/softhsm2.conf
              
              # Initialize SoftHSM token if it doesn't exist
              if [ ! -f "/softhsm/tokens/.initialized" ]; then
                echo "Initializing SoftHSM token..."
                softhsm2-util --init-token --slot 0 --label "{{ .Values.softhsm.pin.tokenLabel }}" --so-pin "{{ .Values.softhsm.pin.sopin }}" --pin "{{ .Values.softhsm.pin.userpin }}"
                touch /softhsm/tokens/.initialized
              fi
              
              # Start a simple keep-alive process
              while true; do
                sleep 3600
              done
          env:
            - name: SOFTHSM2_CONF
              value: /etc/softhsm2/softhsm2.conf
          volumeMounts:
            - name: config
              mountPath: /etc/softhsm2/softhsm2.conf
              subPath: softhsm2.conf
            - name: softhsm-tokens
              mountPath: /softhsm/tokens
          resources:
            {{- toYaml .Values.softhsm.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vault-pki.fullname" . }}-config
        - name: softhsm-tokens
          {{- if .Values.vault.ha.enabled }}
          hostPath:
            path: /var/softhsm/tokens
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "vault-pki.fullname" . }}-softhsm
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
